# Generated by Django 5.1.1 on 2024-10-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0002_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'low'), ('Medium', 'medium'), ('High', 'high')], default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To Do', 'todo'), ('In Progress', 'in_progress'), ('Done', 'done')], default='To Do', max_length=20),
        ),
    ]
