# Generated by Django 5.1.1 on 2024-10-27 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='creator',
        ),
    ]
